[package]
name = "actuator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device = { path = "../device" }
uuid = { version = "1.6.1", features = ["v4"] }
serde_json = "1.0.108"
serde = "1.0.193"
